general.import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin-frappe.toml"
  #"~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]



[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Full"

opacity = 0.95
blur = true

option_as_alt = "Both"

[selection]
save_to_clipboard     = true

[font]
normal.family = "FiraMono Nerd Font"
bold.family = "FiraMono Nerd Font"
italic.family = "FiraMono Nerd Font"
bold_italic.family = "FiraMono Nerd Font"

size = 16

